import type { Metadata } from "next";
import { SITE_NAME } from "@/constant";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  icons: {
    icon: "/images/favicon.svg",
    apple: "/images/favicon.svg",
  },
  title: {
    absolute: SITE_NAME,
    template: `%s / ${SITE_NAME}`,
    default: SITE_NAME,
  },
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body className="">{children}</body>
      </ThemeProvider>
    </html>
  );
}
