import type { Metadata } from "next";
import { SITE_NAME } from "@/constant";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  icons: {
    icon: "/images/favicon.svg",
    apple: "/images/favicon.svg",
  },
  title: {
    absolute: SITE_NAME,
    template: `%s / ${SITE_NAME}`,
    default: SITE_NAME,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
